ExpeditionConfig = ExpeditionConfig or {}

ExpeditionConfig.OPCODE = 113

-- Runtime storage (not DB storages.xml) for expedition flags.
ExpeditionConfig.STORAGE_ACTIVE = 910001
ExpeditionConfig.STORAGE_EXPEDITION_ID = 910002
ExpeditionConfig.STORAGE_RETURN_X = 910003
ExpeditionConfig.STORAGE_RETURN_Y = 910004
ExpeditionConfig.STORAGE_RETURN_Z = 910005
ExpeditionConfig.STORAGE_SLOT = 910006

-- Mirrors apps/canary/src/map/map_const.hpp (not exposed to Lua).
ExpeditionConfig.MAP_MAX_CLIENT_VIEW_PORT_X = 16
ExpeditionConfig.MAP_MAX_CLIENT_VIEW_PORT_Y = 10
-- Full client-visible rectangle with the player at the center.
ExpeditionConfig.MAP_WIDTH = ExpeditionConfig.MAP_MAX_CLIENT_VIEW_PORT_X * 2 + 1
ExpeditionConfig.MAP_HEIGHT = ExpeditionConfig.MAP_MAX_CLIENT_VIEW_PORT_Y * 2 + 1

-- Private instance grid far from the live world. Each player gets a viewport-sized slot.
ExpeditionConfig.INSTANCE_BASE_X = 60000
ExpeditionConfig.INSTANCE_BASE_Y = 60000
ExpeditionConfig.INSTANCE_Z = 7
-- Keep slots well beyond client viewport so concurrent players never see each other.
ExpeditionConfig.SLOT_SIZE = math.max(ExpeditionConfig.MAP_WIDTH, ExpeditionConfig.MAP_HEIGHT) + ExpeditionConfig.MAP_MAX_CLIENT_VIEW_PORT_X * 2
ExpeditionConfig.MAX_SLOTS = 32
ExpeditionConfig.BORDER_ITEM_ID = 2256 -- mountain wall
ExpeditionConfig.AI_TICK_MS = 1000
ExpeditionConfig.WAVE_RESPAWN_MS = 8000
-- Classic Tibia spawn flash (matches SpawnMonster::NONBLOCKABLE_SPAWN_MONSTER_INTERVAL).
ExpeditionConfig.PRE_SPAWN_FLASHES = 3
ExpeditionConfig.PRE_SPAWN_INTERVAL_MS = 1400
ExpeditionConfig.FALLBACK_GROUND_ID = 4526 -- grass
-- Player-selectable spawn intensity (creatures per wave).
ExpeditionConfig.LURE_MIN = 1
ExpeditionConfig.LURE_MAX = 8
ExpeditionConfig.LURE_DEFAULT = 1

-- BEGIN GENERATED EXPEDITION CATALOG
-- Generated by packages/asset-pipeline map:expedition:catalog — do not edit by hand.
ExpeditionConfig.Catalog = {
	{
		id = "thais_sewers",
		name = "Thais Sewers",
		city = "Thais",
		band = "1-7",
		levelMin = 1,
		recommendedLevel = 6,
		bandEntry = true,
		expstar = 1,
		lootstar = 1,
		region = "thais_sewers",
		creatures = {
			"Cave Rat",
			"Rat",
		},
	},
	{
		id = "folda",
		name = "Folda",
		city = "Carlin",
		band = "1-7",
		levelMin = 7,
		recommendedLevel = 7,
		bandEntry = false,
		expstar = 4,
		lootstar = 3,
		region = "folda",
		creatures = {
			"Frost Dragon",
			"Frost Dragon Hatchling",
		},
	},
	{
		id = "swamp_troll_cave",
		name = "Swamp Troll Cave",
		city = "Venore",
		band = "1-7",
		levelMin = 7,
		recommendedLevel = 7,
		bandEntry = false,
		expstar = 4,
		lootstar = 3,
		region = "swamp_troll_cave",
		creatures = {
			"Swamp Troll",
		},
	},
	{
		id = "dusalks_troll_clan_cave",
		name = "Dusalk's Troll Clan Cave",
		city = "Kazordoon",
		band = "8-19",
		levelMin = 8,
		recommendedLevel = 8,
		bandEntry = true,
		expstar = 3,
		lootstar = 3,
		region = "dusalks_troll_clan_cave",
		creatures = {
			"Troll",
			"Troll Champion",
		},
	},
	{
		id = "treasure_island",
		name = "Treasure Island",
		city = "Liberty Bay",
		band = "8-19",
		levelMin = 10,
		recommendedLevel = 10,
		bandEntry = false,
		expstar = 4,
		lootstar = 4,
		region = "treasure_island",
		creatures = {
			"Blood Crab",
		},
	},
	{
		id = "mount_sternum_undead_cave",
		name = "Mount Sternum Undead Cave",
		city = "Thais",
		band = "8-19",
		levelMin = 13,
		recommendedLevel = 13,
		bandEntry = false,
		expstar = 4,
		lootstar = 5,
		region = "mount_sternum_undead_cave",
		creatures = {
			"Ghoul",
			"Skeleton",
		},
	},
	{
		id = "dark_cathedral",
		name = "Dark Cathedral",
		city = "Venore",
		band = "20-34",
		levelMin = 20,
		recommendedLevel = 20,
		bandEntry = true,
		expstar = 5,
		lootstar = 4,
		region = "dark_cathedral",
		creatures = {
			"Banshee",
			"Dark Torturer",
			"Demon",
			"Lost Soul",
		},
	},
	{
		id = "banuta",
		name = "Banuta",
		city = "Port Hope",
		band = "20-34",
		levelMin = 30,
		recommendedLevel = 30,
		bandEntry = false,
		expstar = 4,
		lootstar = 5,
		region = "banuta",
		creatures = {
			"Kongra",
			"Sibang",
		},
	},
	{
		id = "cyclopolis",
		name = "Cyclopolis",
		city = "Edron",
		band = "20-34",
		levelMin = 34,
		recommendedLevel = 34,
		bandEntry = false,
		expstar = 5,
		lootstar = 4,
		region = "cyclopolis",
		creatures = {
			"Behemoth",
			"Cyclops",
			"Cyclops Drone",
			"Cyclops Smith",
			"Dwarf Soldier",
		},
	},
	{
		id = "alchemist_quarter",
		name = "Alchemist Quarter",
		city = "Yalahar",
		band = "35-49",
		levelMin = 35,
		recommendedLevel = 35,
		bandEntry = true,
		expstar = 4,
		lootstar = 4,
		region = "alchemist_quarter",
		creatures = {
			"Mercury Blob",
			"Mutated Human",
		},
	},
	{
		id = "dragonblaze_peaks",
		name = "Dragonblaze Peaks",
		city = "Farmine",
		band = "35-49",
		levelMin = 40,
		recommendedLevel = 40,
		bandEntry = false,
		expstar = 5,
		lootstar = 3,
		region = "dragonblaze_peaks",
		creatures = {
			"Dragon",
			"Dragon Hatchling",
		},
	},
	{
		id = "poacher_caves",
		name = "Poacher Caves",
		city = "Venore",
		band = "35-49",
		levelMin = 40,
		recommendedLevel = 40,
		bandEntry = false,
		expstar = 5,
		lootstar = 3,
		region = "poacher_caves",
		creatures = {
			"Orc Warrior",
			"Poacher",
			"Rorc",
		},
	},
	{
		id = "edron_vampire_crypt",
		name = "Edron Vampire Crypt",
		city = "Edron",
		band = "50-79",
		levelMin = 50,
		recommendedLevel = 50,
		bandEntry = true,
		expstar = 4,
		lootstar = 4,
		region = "edron_vampire_crypt",
		creatures = {
			"Vampire",
			"Vampire Bride",
			"Vampire Viscount",
		},
	},
	{
		id = "corym_mines",
		name = "Corym Mines",
		city = "Venore",
		band = "50-79",
		levelMin = 60,
		recommendedLevel = 60,
		bandEntry = false,
		expstar = 5,
		lootstar = 4,
		region = "corym_mines",
		creatures = {
			"Stonerefiner",
		},
	},
	{
		id = "muggy_plains",
		name = "Muggy Plains",
		city = "Farmine",
		band = "50-79",
		levelMin = 60,
		recommendedLevel = 60,
		bandEntry = false,
		expstar = 5,
		lootstar = 5,
		region = "muggy_plains",
		creatures = {
			"Dragon Hatchling",
			"Lizard Dragon Priest",
			"Lizard High Guard",
			"Lizard Legionnaire",
		},
	},
	{
		id = "drefia_wyrm_lair",
		name = "Drefia Wyrm Lair",
		city = "Darashia",
		band = "80-99",
		levelMin = 80,
		recommendedLevel = 80,
		bandEntry = false,
		expstar = 5,
		lootstar = 4,
		region = "drefia_wyrm_lair",
		creatures = {
			"Elder Wyrm",
			"Wyrm",
		},
	},
	{
		id = "vandura_mountain",
		name = "Vandura Mountain",
		city = "Liberty Bay",
		band = "80-99",
		levelMin = 80,
		recommendedLevel = 80,
		bandEntry = true,
		expstar = 5,
		lootstar = 5,
		region = "vandura_mountain",
		creatures = {
			"Behemoth",
		},
	},
	{
		id = "deeper_banuta",
		name = "Deeper Banuta",
		city = "Port Hope",
		band = "80-99",
		levelMin = 90,
		recommendedLevel = 90,
		bandEntry = false,
		expstar = 5,
		lootstar = 5,
		region = "deeper_banuta",
		creatures = {
			"Eternal Guardian",
			"Hydra",
			"Medusa",
			"Serpent Spawn",
			"Souleater",
		},
	},
	{
		id = "yielothax_dimension",
		name = "Yielothax Dimension",
		city = "Farmine",
		band = "100-149",
		levelMin = 100,
		recommendedLevel = 100,
		bandEntry = true,
		expstar = 5,
		lootstar = 5,
		region = "yielothax_dimension",
		creatures = {
			"Yielothax",
		},
	},
	{
		id = "medusa_cave",
		name = "Medusa Cave",
		city = "Liberty Bay",
		band = "100-149",
		levelMin = 120,
		recommendedLevel = 120,
		bandEntry = false,
		expstar = 5,
		lootstar = 5,
		region = "medusa_cave",
		creatures = {
			"Medusa",
			"Serpent Spawn",
		},
	},
	{
		id = "yakchal_crypt",
		name = "Yakchal Crypt",
		city = "Svargrond",
		band = "100-149",
		levelMin = 130,
		recommendedLevel = 130,
		bandEntry = false,
		expstar = 5,
		lootstar = 5,
		region = "yakchal_crypt",
		creatures = {
			"Ice Witch",
		},
	},
	{
		id = "court_of_summer",
		name = "Court of Summer",
		city = "Feyrist",
		band = "150-199",
		levelMin = 150,
		recommendedLevel = 150,
		bandEntry = false,
		expstar = 4,
		lootstar = 4,
		region = "court_of_summer",
		creatures = {
			"Crazed Summer Rearguard",
			"Insane Siren",
		},
	},
	{
		id = "court_of_winter",
		name = "Court of Winter",
		city = "Svargrond",
		band = "150-199",
		levelMin = 150,
		recommendedLevel = 150,
		bandEntry = false,
		expstar = 4,
		lootstar = 4,
		region = "court_of_winter",
		creatures = {
			"Crazed Winter Rearguard",
			"Crazed Winter Vanguard",
			"Thanatursus",
		},
	},
	{
		id = "drefia_grim_reaper_dungeons",
		name = "Drefia Grim Reaper Dungeons",
		city = "Darashia",
		band = "150-199",
		levelMin = 150,
		recommendedLevel = 150,
		bandEntry = true,
		expstar = 5,
		lootstar = 4,
		region = "drefia_grim_reaper_dungeons",
		creatures = {
			"Banshee",
			"Grim Reaper",
			"Spectre",
		},
	},
	{
		id = "asura_palace",
		name = "Asura Palace",
		city = "Port Hope",
		band = "200-249",
		levelMin = 200,
		recommendedLevel = 200,
		bandEntry = true,
		expstar = 5,
		lootstar = 5,
		region = "asura_palace",
		creatures = {
			"Dawnfire Asura",
			"Midnight Asura",
		},
	},
	{
		id = "guzzlemaw_valley",
		name = "Guzzlemaw Valley",
		city = "Roshamuul",
		band = "200-249",
		levelMin = 200,
		recommendedLevel = 200,
		bandEntry = false,
		expstar = 5,
		lootstar = 5,
		region = "guzzlemaw_valley",
		creatures = {
			"Frazzlemaw",
			"Guzzlemaw",
			"Silencer",
		},
	},
	{
		id = "haunted_cellar",
		name = "Haunted Cellar",
		city = "Venore",
		band = "200-249",
		levelMin = 200,
		recommendedLevel = 200,
		bandEntry = false,
		expstar = 4,
		lootstar = 4,
		region = "haunted_cellar",
		creatures = {
			"Arachnophobica",
			"Ripper Spectre",
		},
	},
	{
		id = "ancient_ancestorial_grounds",
		name = "Ancient Ancestorial Grounds",
		city = "Gray Beach",
		band = "250-299",
		levelMin = 250,
		recommendedLevel = 250,
		bandEntry = false,
		expstar = 5,
		lootstar = 4,
		region = "ancient_ancestorial_grounds",
		creatures = {
			"Deathling Scout",
			"Deathling Spellsinger",
		},
	},
	{
		id = "deep_desert",
		name = "Deep Desert",
		city = "Darashia",
		band = "250-299",
		levelMin = 250,
		recommendedLevel = 250,
		bandEntry = true,
		expstar = 5,
		lootstar = 5,
		region = "deep_desert",
		creatures = {
			"Skeleton Elite Warrior",
			"Undead Elite Gladiator",
		},
	},
	{
		id = "roshamuul_prison",
		name = "Roshamuul Prison",
		city = "Roshamuul",
		band = "250-299",
		levelMin = 250,
		recommendedLevel = 250,
		bandEntry = false,
		expstar = 5,
		lootstar = 4,
		region = "roshamuul_prison",
		creatures = {
			"Blightwalker",
			"Dark Torturer",
			"Demon Outcast",
			"Energy Elemental",
			"Hellhound",
		},
	},
	{
		id = "asura_vaults",
		name = "Asura Vaults",
		city = "Port Hope",
		band = "300-399",
		levelMin = 300,
		recommendedLevel = 300,
		bandEntry = false,
		expstar = 4,
		lootstar = 5,
		region = "asura_vaults",
		creatures = {
			"Hellhound",
			"Hellspawn",
			"True Dawnfire Asura",
			"True Midnight Asura",
		},
	},
	{
		id = "barren_drift",
		name = "Barren Drift",
		city = "Edron",
		band = "300-399",
		levelMin = 300,
		recommendedLevel = 300,
		bandEntry = false,
		expstar = 3,
		lootstar = 2,
		region = "barren_drift",
		creatures = {
			"Cursed Prospector",
			"Evil Prospector",
		},
	},
	{
		id = "cobra_bastion",
		name = "Cobra Bastion",
		city = "Ankrahmun",
		band = "300-399",
		levelMin = 300,
		recommendedLevel = 300,
		bandEntry = true,
		expstar = 5,
		lootstar = 4,
		region = "cobra_bastion",
		creatures = {
			"Cobra Assassin",
			"Cobra Scout",
			"Cobra Vizier",
		},
	},
	{
		id = "bulltaur_lair",
		name = "Bulltaur Lair",
		city = "Venore",
		band = "400-549",
		levelMin = 400,
		recommendedLevel = 400,
		bandEntry = false,
		expstar = 3,
		lootstar = 3,
		region = "bulltaur_lair",
		creatures = {
			"Skeleton Elite Warrior",
			"Undead Elite Gladiator",
		},
	},
	{
		id = "iksupan_last_stand",
		name = "Iksupan Last Stand",
		city = "Port Hope",
		band = "400-549",
		levelMin = 400,
		recommendedLevel = 400,
		bandEntry = false,
		expstar = 0,
		lootstar = 0,
		region = "iksupan_last_stand",
		creatures = {
			"Cursed Ape",
			"Iks Aucar",
			"Iks Chuka",
			"Iks Pututu",
		},
	},
	{
		id = "temple_of_the_moon_goddess",
		name = "Temple of the Moon Goddess",
		city = "Marapur",
		band = "400-549",
		levelMin = 400,
		recommendedLevel = 400,
		bandEntry = true,
		expstar = 5,
		lootstar = 3,
		region = "temple_of_the_moon_goddess",
		creatures = {
			"Makara",
			"Naga Archer",
			"Naga Warrior",
		},
	},
	{
		id = "norcferatu_dungeons",
		name = "Norcferatu Dungeons",
		city = "Yalahar",
		band = "550-599",
		levelMin = 550,
		recommendedLevel = 550,
		bandEntry = true,
		expstar = 2,
		lootstar = 2,
		region = "norcferatu_dungeons",
		creatures = {
			"Spectre",
			"Werewolf",
		},
	},
	{
		id = "claustrophobic_inferno",
		name = "Claustrophobic Inferno",
		city = "Kilmaresh",
		band = "600+",
		levelMin = 600,
		recommendedLevel = 600,
		bandEntry = false,
		expstar = 0,
		lootstar = 0,
		region = "claustrophobic_inferno",
		creatures = {
			"Brachiodemon",
			"Infernal Demon",
			"Infernal Phantom",
		},
	},
	{
		id = "ebb_and_flow",
		name = "Ebb and Flow",
		city = "Kilmaresh",
		band = "600+",
		levelMin = 600,
		recommendedLevel = 600,
		bandEntry = true,
		expstar = 5,
		lootstar = 4,
		region = "ebb_and_flow",
		creatures = {
			"Bony Sea Devil",
			"Capricious Phantom",
			"Turbulent Elemental",
		},
	},
	{
		id = "furious_crater",
		name = "Furious Crater",
		city = "Kilmaresh",
		band = "600+",
		levelMin = 600,
		recommendedLevel = 600,
		bandEntry = false,
		expstar = 4,
		lootstar = 4,
		region = "furious_crater",
		creatures = {
			"Cloak of Terror",
			"Courage Leech",
			"Vibrant Phantom",
		},
	},
}
-- END GENERATED EXPEDITION CATALOG

function ExpeditionConfig.getById(id)
	for _, entry in ipairs(ExpeditionConfig.Catalog) do
		if entry.id == id then
			return entry
		end
	end
	return nil
end

function ExpeditionConfig.catalogForClient()
	local out = {}
	for _, entry in ipairs(ExpeditionConfig.Catalog) do
		out[#out + 1] = {
			id = entry.id,
			name = entry.name,
			city = entry.city,
			band = entry.band,
			levelMin = entry.levelMin,
			recommendedLevel = entry.recommendedLevel,
			bandEntry = entry.bandEntry,
			expstar = entry.expstar,
			lootstar = entry.lootstar,
			creatures = entry.creatures,
		}
	end
	return out
end

function ExpeditionConfig.chunkDir(region)
	return DATA_DIRECTORY .. "/world/expeditions/" .. region
end

function ExpeditionConfig.loadManifest(region)
	local path = ExpeditionConfig.chunkDir(region) .. "/manifest.json"
	local file = io.open(path, "r")
	if not file then
		return nil
	end
	local content = file:read("*a")
	file:close()
	return ExpeditionJson.decode(content)
end
